### PR TITLE
Add rio terminal status

### PR DESCRIPTION
**Pull request by raphamorim**

### CODE REVIEW

**Comment by smasher164** [comment]
Thanks for submitting this. This list should be in alphabetical order, so can you move `Rio terminal` right before `Rlogin`?
Additionally, if possible, run `hugo -D` to generate the html. If not, that's fine--I can do it on my end.

**Comment by raphamorim** [comment]
For sure @smasher164 !! Thank you for your review! Feel free to update or I can do it Monday as well 🙏

**Comment by raphamorim** [comment]
@smasher164 sorry for delay, I've updated the file but when I tried to run `hugo -D` but didn't build the html, got this message though

```
WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

I am using this hugo version

```
hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended darwin/arm64 BuildDate=2023-12-08T08:47:45Z VendorInfo=brew
```

**Comment by smasher164** [comment]
No worries @raphamorim. Thanks for making the update. I'll fix the hugo situation one of these days.

**Comment by raphamorim** [comment]
Thank you @smasher164 🙏

**Pull request merged**
